### ISSUE TITLE
Can't list scheduled scans

### ISSUE THREAD

**Issue by pemontto** [paragbaxi/qualysapi#22]
It appears the scheduled scans endpoint for some reason doesn't take POST requests for listing scans... no idea why. The request needs to be performed as a GET with URL parameters instead.

```xml
>>> parameters = {'action': 'list', 'echo_request': 1}
>>> call = 'api/2.0/fo/schedule/scan/'
>>> xml_output = qgc.request(call, parameters)
DEBUG:qualysapi.connector:api_call =
api/2.0/fo/schedule/scan/
DEBUG:qualysapi.connector:api_version =
None
DEBUG:qualysapi.connector:data <type 'dict'> =
 {'action': 'list', 'echo_request': 1}
DEBUG:qualysapi.connector:http_method =
None
DEBUG:qualysapi.connector:concurrent_scans_retries =
0
DEBUG:qualysapi.connector:concurrent_scans_retry_delay =
0
DEBUG:qualysapi.connector:Base url =
https://qualysapi.qg3.apps.qualys.com/
DEBUG:qualysapi.connector:headers =
{'X-Requested-With': 'Parag Baxi QualysAPI (python) v4.1.0'}
DEBUG:qualysapi.connector:http_method =
post
DEBUG:qualysapi.connector:api_call post strip =
api/2.0/fo/schedule/scan/
DEBUG:qualysapi.connector:api_call =
api/2.0/fo/schedule/scan/
DEBUG:qualysapi.connector:url =
https://qualysapi.qg3.apps.qualys.com/api/2.0/fo/schedule/scan/
DEBUG:qualysapi.connector:data =
{'action': 'list', 'echo_request': 1}
DEBUG:qualysapi.connector:headers =
{'X-Requested-With': 'Parag Baxi QualysAPI (python) v4.1.0'}
DEBUG:qualysapi.connector:POST request.
DEBUG:qualysapi.connector:response headers =
{'X-RateLimit-Remaining': '288', 'X-XSS-Protection': '1', 'X-Content-Type-Options': 'nosniff', 'X-Concurrency-Limit-Limit': '2', 'Transfer-Encoding': 'chunked', 'Server': 'Qualys', 'X-Concurrency-Limit-Running': '0', 'Connection': 'close', 'X-RateLimit-Limit': '300', 'X-RateLimit-ToWait-Sec': '0', 'Date': 'Tue, 13 Jun 2017 14:45:53 GMT', 'Content-Type': 'text/xml;charset=UTF-8', 'X-RateLimit-Window-Sec': '3600'}
DEBUG:qualysapi.connector:rate limit for api_call, api/2.0/fo/schedule/scan/ = 288
DEBUG:qualysapi.connector:response text =
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE SIMPLE_RETURN SYSTEM "https://qualysapi.qg3.apps.qualys.com/api/2.0/simple_return.dtd">
<SIMPLE_RETURN>
  <REQUEST>
    <DATETIME>2017-06-13T14:45:53Z</DATETIME>
    <USER_LOGIN>user</USER_LOGIN>
    <RESOURCE>https://qualysapi.qg3.apps.qualys.com/api/2.0/fo/schedule/scan/</RESOURCE>
    <PARAM_LIST>
      <PARAM>
        <KEY>action</KEY>
        <VALUE>list</VALUE>
      </PARAM>
      <PARAM>
        <KEY>echo_request</KEY>
        <VALUE>1</VALUE>
      </PARAM>
    </PARAM_LIST>
  </REQUEST>
  <RESPONSE>
    <DATETIME>2017-06-13T14:45:53Z</DATETIME>
    <CODE>1908</CODE>
    <TEXT>Request method POST is incompatible with specified parameter(s): action=list</TEXT>
  </RESPONSE>
</SIMPLE_RETURN>

Error! Received a 4XX client error or 5XX server error response.
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/qualysapi/connector.py", line 343, in request
    request.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://qualysapi.qg3.apps.qualys.com/api/2.0/fo/schedule/scan/
```

**Comment by pemontto** [comment]
Can workaround this by specifying the http_method

```python
qgc.request(call, parameters, api_version=2, http_method='get')
```
