### ISSUE TITLE
chardet MemoryError

### ISSUE THREAD

**Issue by pabb85** [paragbaxi/qualysapi#53]
Whilst porting some basic scripts over to AWS, we are encountering an issue relating to the chardet detection which ultimately crashes the script.  This does not affect the original script running on the windows box.

Error is as follows;

```
ubuntu@XXXXX:~$ time ./KB-AWS-test.py -d
Downloading KB...
Traceback (most recent call last):
  File "./KB-AWS-test.py", line 41, in <module>
    downloadKB()
  File "./KB-AWS-test.py", line 26, in downloadKB
    print a.request(call, parameters)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/qualysapi/connector.py", line 327, in request
    response = request.text
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/models.py", line 857, in text
    encoding = self.apparent_encoding
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/models.py", line 727, in apparent_encoding
    return chardet.detect(self.content)['encoding']
  File "/home/ubuntu/.local/lib/python2.7/site-packages/chardet/__init__.py", line 38, in detect
    detector.feed(byte_str)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/chardet/universaldetector.py", line 211, in feed
    if prober.feed(byte_str) == ProbingState.FOUND_IT:
  File "/home/ubuntu/.local/lib/python2.7/site-packages/chardet/charsetgroupprober.py", line 71, in feed
    state = prober.feed(byte_str)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/chardet/hebrewprober.py", line 227, in feed
    byte_str = self.filter_high_byte_only(byte_str)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/chardet/charsetprober.py", line 63, in filter_high_byte_only
    buf = re.sub(b'([\x00-\x7F])+', b' ', buf)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
MemoryError

real    22m2.627s
user    13m54.835s
sys     0m8.815s

```

The script responsible for the crash is as follows;
```
#!/usr/bin/env python

import qualysapi
from optparse import OptionParser
import sys

def downloadKB():
        print 'Downloading KB...'
        a = qualysapi.connect()
        call = '/api/2.0/fo/knowledge_base/vuln/'
        parameters = {'action': 'list'}
        print a.request(call, parameters)

        #write file at once - takes a while and no feedback, build out chunking/feedback procedure...TODO
        #f = open('KB.xml', 'w')
        #f.write(a.request(call, parameters))
        #f.close()
        return

####  MAIN  ####

parser = OptionParser()
parser.add_option("-d", action="store_true", dest="downloadFlag")
(options, args) = parser.parse_args()

if options.downloadFlag:
        downloadKB()

```

It is similar to experienced with chardet elsewhere ([(https://github.com/sentinelsat/sentinelsat/issues/150)]) and can be resolved by forcing encoding type on response?

**Comment by paragbaxi** [comment]
If you throw in a patch, I can merge.

**Comment by pabb85** [comment]
Thanks @paragbaxi 
```

$ diff connector.py connector-edited.py
327c327
<             response = request.text
---
>             response = request.content.decode("utf8")
```

The above should do the trick, certainly resolved the issue for me.

**Comment by paragbaxi** [comment]
Can you throw this in a PR?
